import { useMemo, useState } from 'react'

const INITIAL_ITEMS = [
  { id: 1, name: 'Sony Alpha Camera', category: 'Kamera', price: 150000, status: 'Aktif', image: '📷', rented: 24 },
  { id: 2, name: 'PlayStation 5', category: 'Gaming', price: 100000, status: 'Aktif', image: '🎮', rented: 18 },
  { id: 3, name: 'Camping Tent', category: 'Outdoor', price: 75000, status: 'Tersewa', image: '⛺', rented: 12 },
  { id: 4, name: 'DJI Mini Drone', category: 'Kamera', price: 220000, status: 'Aktif', image: '🚁', rented: 9 },
  { id: 5, name: 'Mountain Bike', category: 'Olahraga', price: 90000, status: 'Nonaktif', image: '🚲', rented: 7 },
]

export default function SellerItems() {
  const [items, setItems] = useState(INITIAL_ITEMS)
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('Semua Status')
  const [showForm, setShowForm] = useState(false)
  const [editing, setEditing] = useState(null)
  const visibleItems = useMemo(() => items.filter((item) => item.name.toLowerCase().includes(query.toLowerCase()) && (status === 'Semua Status' || item.status === status)), [items, query, status])
  const saveListing = (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const listing = { id: editing?.id || Date.now(), name: data.get('name'), category: data.get('category'), price: Number(data.get('price')), status: data.get('status'), image: '📦', rented: editing?.rented || 0 }; setItems((current) => editing ? current.map((item) => item.id === editing.id ? listing : item) : [listing, ...current]); setEditing(null); setShowForm(false) }
  return <div className="seller-items"><div className="items-header"><div><p className="section-kicker">Manajemen listing</p><h1>Barang Saya</h1><p>Kelola ketersediaan dan performa barang sewaan Anda.</p></div><button className="btn-primary" onClick={() => { setEditing(null); setShowForm(true) }}>+ Tambah listing</button></div>{showForm && <form className="listing-form" onSubmit={saveListing}><div className="form-heading"><h2>{editing ? 'Edit listing' : 'Tambah listing baru'}</h2><button type="button" className="btn-small" onClick={() => setShowForm(false)}>Tutup</button></div><label>Nama barang<input required name="name" defaultValue={editing?.name} placeholder="Contoh: Sony Alpha Camera" /></label><label>Kategori<select name="category" defaultValue={editing?.category || 'Kamera'}><option>Kamera</option><option>Gaming</option><option>Outdoor</option><option>Olahraga</option><option>Elektronik</option></select></label><label>Harga sewa per hari<input required name="price" type="number" min="0" defaultValue={editing?.price} /></label><label>Status<select name="status" defaultValue={editing?.status || 'Aktif'}><option>Aktif</option><option>Nonaktif</option></select></label><label className="form-wide">Deskripsi<textarea placeholder="Jelaskan kondisi, kelengkapan, dan aturan sewa" /></label><label>Deposit keamanan<input type="number" min="0" placeholder="Contoh: 500000" /></label><label>Lokasi<input placeholder="Jakarta Selatan" /></label><button className="btn-primary form-submit">Simpan listing</button></form>}<div className="items-filters"><input value={query} onChange={(event) => setQuery(event.target.value)} type="search" placeholder="Cari listing..." className="search-box-small" /><select value={status} onChange={(event) => setStatus(event.target.value)} className="filter-select"><option>Semua Status</option><option>Aktif</option><option>Tersewa</option><option>Nonaktif</option></select></div><div className="items-grid">{visibleItems.map((item) => <article key={item.id} className="item-card"><div className="item-image-large">{item.image}</div><div className="item-details"><span className={`status-badge ${item.status.toLowerCase()}`}>{item.status}</span><h3 className="item-title">{item.name}</h3><p className="item-category">{item.category}</p><div className="item-info"><p><span>Harga sewa</span><strong>Rp {item.price.toLocaleString('id-ID')}/hari</strong></p><p><span>Total disewa</span><strong>{item.rented}x</strong></p></div><div className="item-actions"><button className="btn-small" onClick={() => { setEditing(item); setShowForm(true) }}>Edit</button><button className="btn-small" onClick={() => alert(`Detail ${item.name}`)}>Lihat</button><button className="btn-small btn-danger" onClick={() => setItems((current) => current.filter((listing) => listing.id !== item.id))}>Hapus</button></div></div></article>)}{!visibleItems.length && <p className="empty-state">Tidak ada listing yang sesuai.</p>}</div></div>
}
